#!/bin/sh
#
# @name COEX Clover 4
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Oleg Kalachev <okalachev@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MC_PITCHRATE_P 0.087
param set-default MC_PITCHRATE_I 0.037
param set-default MC_PITCHRATE_D 0.0044
param set-default MC_PITCH_P 8.5
param set-default MC_ROLLRATE_P 0.087
param set-default MC_ROLLRATE_I 0.037
param set-default MC_ROLLRATE_D 0.0044
param set-default MC_ROLL_P 8.5
param set-default MPC_XY_VEL_P_ACC 2.2
param set-default MPC_XY_VEL_D_ACC 0.26
param set-default MPC_XY_P 1.1
param set-default MPC_Z_VEL_P_ACC 4.8
param set-default MPC_Z_P 1.2

param set-default BAT1_N_CELLS 4

param set-default CAL_MAG_SIDES 34 # calibrate mag by 2 sides

param set-default COM_FLTMODE1 8	
param set-default COM_FLTMODE2 8	
param set-default COM_FLTMODE3 1	
param set-default COM_FLTMODE4 1	
param set-default COM_FLTMODE5 2	
param set-default COM_FLTMODE6 2

param set-default EKF2_AID_MASK 24 # vis pos + vis yaw
param set-default EKF2_HGT_MODE 3 # vision

param set-default MAV_1_CONFIG 102	
param set-default MAV_1_FORWARD 0	
param set-default MAV_1_MODE 2	
param set-default MAV_1_RADIO_CTL 1	
param set-default MAV_1_RATE 80000

param set-default SENS_BOARD_ROT 10
param set-default RC_MAP_ARM_SW 7
param set-default RC_MAP_FLTMODE 5
param set-default RC_MAP_KILL_SW 8
param set-default RC_MAP_OFFB_SW 6
param set-default RC_MAP_PITCH 2
param set-default RC_MAP_ROLL 1
param set-default RC_MAP_YAW 4
param set-default RC_MAP_THROTTLE 3
param set-default RC_CHAN_CNT 8

param set-default NAV_DLL_ACT 3 # LAND MODE
param set-default NAV_RCL_ACT 3 # LAND MODE
param set-default GF_ACTION 5 # LAND MODE
